In [2]:
from numpy.linalg import inv, solve, norm, cond, det
import numpy as np
from prettytable import PrettyTable

In [9]:
class ConditionNumber:
    def __init__(self, matrix, vector, solution):
        self.matrix = matrix
        self.vector = vector
        self.solution = solution

    def SpectralCriterion(self, variation = 0):
        mtrx = self.matrix - variation
        return norm(mtrx)*norm(inv(mtrx))

    def VolumetricCriterion(self, variation = 0):
        var_matrix = self.matrix - variation
        determinant = det((var_matrix))
        product = 1
        for i in range(len(var_matrix)):
            sum = 0
            for j in range(len(var_matrix)):
                sum += var_matrix[i][j]**2
            product *= np.sqrt(sum)
        return determinant/np.abs(product)

    def AngleCriterion(self, variation = 0):
        var_matrix = self.matrix - variation
        C = inv(var_matrix)
        return max([norm(a_n)*norm(c_n) for a_n, c_n in zip(var_matrix,np.transpose(C))])

In [10]:
def hilbert_matrix(n: int):
    matrix = np.zeros((n, n))
    for i in range(1, n + 1):
        for j in range(1, n + 1):
            matrix[i - 1][j - 1] = 1 / (i + j - 1)
    return matrix

In [11]:
equations = []
#вариант 1 из методички Пакулиной
A1 = np.array([[-400.6, 199.8],
     [1198.8, -600.4]])
b1 = np.array([200, -600])
exact_x1 = np.array([-0.2, 0.6])

equations.append({"matrix": A1,
                  "vector": b1,
                  "solution": exact_x1})

#матрица Гильберта 3*3
A2 = hilbert_matrix(3)
b2 = np.random.random(3)
exact_x2 = solve(A2, b2)

equations.append({"matrix": A2,
                  "vector": b2,
                  "solution": exact_x2})

#матрица Гильберта 5*5
A3 = hilbert_matrix(5)
b3 = np.random.random(5)
exact_x3 = solve(A3, b3)

equations.append({"matrix": A3,
                  "vector": b3,
                  "solution": exact_x3})

#диагональная матрица
A4 = np.array([[1, 0, 0],
                [0, 1/2, 0],
                [0, 0, 1/3]])
b4 = np.random.random(3)
exact_x4 = solve(A4, b4)

equations.append({"matrix": A4,
                  "vector": b4,
                  "solution": exact_x4})

#пример из презентации
A5 = np.array([[1, 0.99],
     [0.99, 0.98]])
b5 = np.array([1.99, 1.97])
exact_x5 = np.array([1, 1])

equations.append({"matrix": A5,
                  "vector": b5,
                  "solution": exact_x5})


In [12]:
for equation in equations:
    equation = ConditionNumber(**equation)
    print("Matrix:")
    matrix = equation.matrix
    print(matrix)
    print("Vector:")
    vector = equation.vector
    print(vector)
    print("Exact solution:")
    solution = equation.solution
    print(solution)
    print("Spectral criterion: " + str(equation.SpectralCriterion()))
    print("VolumetricCriterion: " + str(equation.VolumetricCriterion()))
    print("AngleCriterion: " + str(equation.AngleCriterion()))
    th = ['variation', 'norm(x - x*)', 'cond(A)']
    td = [0.01, norm(solution - solve(matrix - 0.01, vector - 0.01)), equation.SpectralCriterion(0.01),
          0.00001, norm(solution - solve(matrix - 0.00001, vector - 0.00001)), equation.SpectralCriterion(0.00001),
          0.00000001, norm(solution - solve(matrix - 0.00000001, vector - 0.00000001)), equation.SpectralCriterion(0.00000001)
    ]
    columns = len(th)
    table = PrettyTable(th)
    td_data = td[:]
    while td_data:
        table.add_row(td_data[:columns])
        td_data = td_data[columns:]
    print(table)

Matrix:
[[-400.6  199.8]
 [1198.8 -600.4]]
Vector:
[ 200 -600]
Exact solution:
[-0.2  0.6]
Spectral criterion: 1998.0020000000195
VolumetricCriterion: 0.0016661112044730382
AngleCriterion: 600.2000330561862
+-----------+-----------------------+--------------------+
| variation |      norm(x - x*)     |      cond(A)       |
+-----------+-----------------------+--------------------+
|    0.01   |  0.010478989513561266 | 1951.1736846629044 |
|   1e-05   | 1.073018588235677e-05 | 1997.9540491426708 |
|   1e-08   | 1.073047538708476e-08 | 1998.0019520479627 |
+-----------+-----------------------+--------------------+
Matrix:
[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]
Vector:
[0.41184867 0.19223475 0.90926948]
Exact solution:
[  24.06427165 -141.5859877   141.42171261]
Spectral criterion: 526.1588210797212
VolumetricCriterion: 0.0013191794224663115
AngleCriterion: 172.88724649319923
+-----------+-----------------------+-------